from __future__ import annotations

import json
import re
from dataclasses import dataclass


@dataclass
class FakeLLM:
    """Deterministic model substitute for learning agent control flow."""

    name: str = "fake-llm"

    def invoke(self, prompt: str) -> str:
        text = prompt.lower()
        if "json" in text or "structured" in text:
            return json.dumps({
                "decision": "answer",
                "confidence": 0.82,
                "reason": "The prompt asked for structured output.",
            })
        if "tool" in text and any(word in text for word in ["calculate", "sum", "multiply"]):
            return "ACTION calculator expression=2+2"
        if "rewrite" in text:
            return re.sub(r"[^a-z0-9 ]+", "", prompt.lower()).strip()
        if "grade" in text:
            return "relevant" if any(word in text for word in ["agent", "rag", "memory"]) else "irrelevant"
        return "This is a concise response generated by FakeLLM for local learning."

    def classify(self, text: str, labels: list[str]) -> str:
        lowered = text.lower()
        for label in labels:
            if label.lower() in lowered:
                return label
        if "?" in text and "retrieve" in labels:
            return "retrieve"
        return labels[0]
